---
# handlers file for challenge1
- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true

- name: Restore SELinux context
  command: restorecon -R /var/www/html
  when: ansible_selinux.status == "enabled"
...
